// JavaScript Document
window.muplis = false;
window.nasezvafahi = 'No definition has been found, dude!';
window.bangudecomp = 'decomposing ...';
window.rimni="la rimni sutysisku";
window.bangubuild = 'Building index...';
window.xuzganalojudri = true;
window.judri = "http://jbovlaste.lojban.org/dict/";
window.cllnotci = 'The Reference Grammar on this topic:';
window.purc = "Last searched: ";
window.bangu=".inglic.";
window.arrcll={
A:["14.6"],
BAI:["9.6"],
BAhE:["19.11"],
BE:["5.7"],
BEI:["5.7"],
BEhO:["5.7"],
BIhE:["18.5"],
BIhI:["14.16"],
BO:["5.3","15.6","18.17"],
BOI:["18.6"],
BU:["17.4"],
BY:["17.2"],
CAI:["13.4"],
CAhA:["10.19"],
CEI:["7.5"],
CEhE:["14.11","16.7"],
CO:["5.8"],
COI:["6.11","13.14"],
CU:["9.2"],
CUhE:["10.24"],
DAhO:["7.13"],
DOI:["13.14"],
DOhU:["13.14"],
FA:["9.3"],
FAhA:["10.2"],
FAhO:["19.15"],
FEhE:["10.11"],
FEhU:["9.5"],
FIhO:["9.5"],
FOI:["17.6"],
FUhA:["18.16"],
FUhE:["19.8"],
FUhO:["19.8"],
GA:["14.5"],
GAhO:["14.16"],
GEhU:["8.3"],
GI:["14.5"],
GIhA:["14.3"],
GOI:["8.3","9.10"],
GOhA:["7.6"],
GUhA:["14.3"],
I:["19.2"],
JA:["14.3"],
JAI:["9.12"],
JOI:["14.14"],
JOhI:["18.15"],
KE:["5.5"],
KEI:["11.1"],
KEhE:["5.5"],
KI:["10.13"],
KOhA:["7.1"],
KOhA2:["7.4"],
KOhA3:["7.2"],
KOhA4:["7.5"],
KOhA5:["7.6"],
KOhA6:["7.3"],
KOhA7:["7.7"],
KU:["6.2","10.1"],
KUhE:["18.6"],
KUhO:["8.1"],
LA:["6.2"],
LAU:["17.5","17.7","17.14"],
LAhE:["6.10"],
LE:["6.2","6.5"],
LEhU:["19.9"],
LI:["18.5"],
LIhU:["19.9"],
LOhO:["18.17"],
LOhU:["19.9"],
LU:["19.9"],
LUhU:["6.10"],
MAI:["18.19","19.1"],
MAhO:["18.6"],
ME:["5.10","18.1"],
MEhU:["5.11"],
MOI:["5.9","17.11","18.11"],
MOhE:["18.18"],
MOhI:["10.8"],
NA:["14.3","15.7"],
NAI:["14.3","15.7"],
NAhE:["15.4"],
NAhU:["18.18"],
NIhE:["18.18"],
NIhO:["19.3"],
NOI:["8.1"],
NU:["11.1"],
NUhA:["18.19"],
NUhI:["14.11","16.7"],
NUhU:["14.11"],
PA:["18.2"],
PEhE:["14.11"],
PEhO:["18.6"],
PU:["10.4"],
RAhO:["7.6"],
ROI:["10.9"],
SA:["19.13"],
SE:["5.1","9.4"],
SEI:["19.12","18.20"],
SEhU:["19.12"],
SI:["19.13"],
SOI:["7.8"],
SU:["19.13"],
TAhE:["10.9"],
TEI:["17.6"],
TEhU:["18.15"],
TO:["19.12"],
TOI:["19.12"],
TUhE:["19.2"],
TUhU:["19.2"],
UI:["13.1"],
UI1:["13.2","13.3"],
UI2:["13.11"],
UI3a:["13.13"],
UI3b:["13.12"],
UI4:["13.6"],
UI5:["13.7"],
UI6:["13.13"],
VA:["10.2"],
VAU:["14.9"],
VEI:["18.5"],
VEhA:["10.5"],
VEhO:["19.5"],
VIhA:["10.7"],
VUhO:["8.8"],
VUhU:["18.5"],
VUhU1:["18.5","14.17","5.9","9.8"],
VUhU2:["18.14"],
VUhU4:["18.15"],
XI:["18.13"],
Y:["19.14"],
ZAhO:["10.10"],
ZEI:["4.6"],
ZEhA:["10.5","10.9"],
ZI:["10.4"],
ZIhE:["8.4"],
ZO:["19.10"],
ZOI:["19.10"],
ZOhU:["16.2","19.4"],
"semau":["9.10"],
"secu'u":["9.10"],
"voi":["8.5"]
};
window.cylylypoicnino = {
"1":{"judri":"chapter-about.html","cmene":"Lojban As We Mangle It In Lojbanistan: About This Book"},
"1.1":{"judri":"chapter-about.html#section-what-is-lojban","cmene":"What is Lojban?"},
"1.2":{"judri":"section-what-is-cll.html","cmene":"What is this book?"},
"1.3":{"judri":"section-conventions.html","cmene":"What are the typographical conventions of this book?"},
"1.4":{"judri":"section-disclaimers.html","cmene":"Disclaimers"},
"1.5":{"judri":"credits.html","cmene":"Acknowledgements and Credits"},
"1.6":{"judri":"section-bibliography.html","cmene":"Informal Bibliography"},
"1.7":{"judri":"section-captions.html","cmene":"Captions to Pictures"},
"1.8":{"judri":"section-copyright.html","cmene":"Boring Legalities"},
"2":{"judri":"chapter-tour.html","cmene":"A Quick Tour of Lojban Grammar, With Diagrams"},
"2.1":{"judri":"chapter-tour.html#section-bridi","cmene":"The concept of the bridi"},
"2.2":{"judri":"section-pronunciation.html","cmene":"Pronunciation"},
"2.3":{"judri":"section-sumti-cmavo.html","cmene":"Words that can act as sumti"},
"2.4":{"judri":"section-some-selbri.html","cmene":"Some words used to indicate selbri relations"},
"2.5":{"judri":"section-some-simple-bridi.html","cmene":"Some simple Lojban bridi"},
"2.6":{"judri":"section-variant-bridi-structure.html","cmene":"Variant bridi structure"},
"2.7":{"judri":"section-order-of-sumti.html","cmene":"Varying the order of sumti"},
"2.8":{"judri":"section-structure-of-utterances.html","cmene":"The basic structure of longer utterances"},
"2.9":{"judri":"section-basic-tanru.html","cmene":"tanru"},
"2.10":{"judri":"section-description-sumti.html","cmene":"Description sumti"},
"2.11":{"judri":"section-some-brivla.html","cmene":"Examples of brivla"},
"2.12":{"judri":"section-dihu-and-lahe-dihu.html","cmene":"The sumti di'u and la'e di'u"},
"2.13":{"judri":"section-possession.html","cmene":"Possession"},
"2.14":{"judri":"section-vocatives-and-commands.html","cmene":"Vocatives and commands"},
"2.15":{"judri":"section-basic-questions.html","cmene":"Questions"},
"2.16":{"judri":"section-attitudinals.html","cmene":"Indicators"},
"2.17":{"judri":"section-tenses.html","cmene":"Tenses"},
"2.18":{"judri":"section-terms.html","cmene":"Lojban grammatical terms"},
"3":{"judri":"chapter-phonology.html","cmene":"The Hills Are Alive With The Sounds Of Lojban"},
"3.1":{"judri":"chapter-phonology.html#section-orthography","cmene":"Orthography"},
"3.2":{"judri":"section-basic-phonetics.html","cmene":"Basic Phonetics"},
"3.3":{"judri":"section-lojban-characters.html","cmene":"The Special Lojban Characters"},
"3.4":{"judri":"section-diphthongs.html","cmene":"Diphthongs and Syllabic Consonants"},
"3.5":{"judri":"section-vowel-pairs.html","cmene":"Vowel Pairs"},
"3.6":{"judri":"section-clusters.html","cmene":"Consonant Clusters"},
"3.7":{"judri":"section-initial-pairs.html","cmene":"Initial Consonant Pairs"},
"3.8":{"judri":"section-buffer-vowels.html","cmene":"Buffering Of Consonant Clusters"},
"3.9":{"judri":"section-stress.html","cmene":"Syllabication And Stress"},
"3.10":{"judri":"section-anglophone-phonetics.html","cmene":"IPA For English Speakers"},
"3.11":{"judri":"section-anglophone-diphthongs.html","cmene":"English Analogues For Lojban Diphthongs"},
"3.12":{"judri":"section-oddball-orthographies.html","cmene":"Oddball Orthographies"},
"4":{"judri":"chapter-morphology.html","cmene":"The Shape Of Words To Come: Lojban Morphology"},
"4.1":{"judri":"chapter-morphology.html#section-morphology-introduction","cmene":"Introductory"},
"4.2":{"judri":"section-cmavo.html","cmene":"cmavo"},
"4.3":{"judri":"section-morphology-brivla.html","cmene":"brivla"},
"4.4":{"judri":"section-gismu.html","cmene":"gismu"},
"4.5":{"judri":"section-lujvo.html","cmene":"lujvo"},
"4.6":{"judri":"section-rafsi.html","cmene":"rafsi"},
"4.7":{"judri":"section-fuhivla.html","cmene":"fu'ivla"},
"4.8":{"judri":"section-cmene.html","cmene":"cmene"},
"4.9":{"judri":"section-pauses.html","cmene":"Rules for inserting pauses"},
"4.10":{"judri":"section-lujvo-considerations.html","cmene":"Considerations for making lujvo"},
"4.11":{"judri":"section-lujvo-making.html","cmene":"The lujvo-making algorithm"},
"4.12":{"judri":"section-lujvo-scoring.html","cmene":"The lujvo scoring algorithm"},
"4.13":{"judri":"section-lujvo-making-examples.html","cmene":"lujvo-making examples"},
"4.14":{"judri":"section-gismu-making.html","cmene":"The gismu creation algorithm"},
"4.15":{"judri":"section-cultural-gismu.html","cmene":"Cultural and other non-algorithmic gismu"},
"4.16":{"judri":"section-rafsi-fuhivla.html","cmene":"rafsi fu'ivla: a proposal"},
"5":{"judri":"chapter-selbri.html","cmene":"Pretty Little Girls' School: The Structure Of Lojban selbri"},
"5.1":{"judri":"chapter-selbri.html#section-content-words-brivla","cmene":"Lojban content words: brivla"},
"5.2":{"judri":"section-simple-tanru.html","cmene":"Simple tanru"},
"5.3":{"judri":"section-three-part-tanru.html","cmene":"Three-part tanru grouping with bo"},
"5.4":{"judri":"section-complex-grouping.html","cmene":"Complex tanru grouping"},
"5.5":{"judri":"section-ke-grouping.html","cmene":"Complex tanru with ke and ke'e"},
"5.6":{"judri":"section-logical-connection.html","cmene":"Logical connection within tanru"},
"5.7":{"judri":"section-be-sumti.html","cmene":"Linked sumti: be-bei-be'o"},
"5.8":{"judri":"section-co-inversion.html","cmene":"Inversion of tanru: co"},
"5.9":{"judri":"section-cmavo-selbri.html","cmene":"Other kinds of simple selbri"},
"5.10":{"judri":"section-me-selbri.html","cmene":"selbri based on sumti: me"},
"5.11":{"judri":"section-place-conversion.html","cmene":"Conversion of simple selbri"},
"5.12":{"judri":"section-selbri-scalar-negation.html","cmene":"Scalar negation of selbri"},
"5.13":{"judri":"section-bridi-negation-tenses.html","cmene":"Tenses and bridi negation"},
"5.14":{"judri":"section-asymmetric-tanru.html","cmene":"Some types of asymmetrical tanru"},
"5.15":{"judri":"section-symmetric-tanru.html","cmene":"Some types of symmetrical tanru"},
"5.16":{"judri":"section-pretty-school-groupings.html","cmene":"Pretty little girls' school: forty ways to say it"},
"6":{"judri":"chapter-sumti.html","cmene":"To Speak Of Many Things: The Lojban sumti"},
"6.1":{"judri":"chapter-sumti.html#section-simple-sumti-kinds","cmene":"The five kinds of simple sumti"},
"6.2":{"judri":"section-basic-descriptors.html","cmene":"The three basic description types"},
"6.3":{"judri":"section-masses.html","cmene":"Individuals and masses"},
"6.4":{"judri":"section-sets.html","cmene":"Masses and sets"},
"6.5":{"judri":"section-typicals.html","cmene":"Descriptors for typical objects"},
"6.6":{"judri":"section-quantified-sumti.html","cmene":"Quantified sumti"},
"6.7":{"judri":"section-quantified-descriptions.html","cmene":"Quantified descriptions"},
"6.8":{"judri":"section-indefinite-descriptions.html","cmene":"Indefinite descriptions"},
"6.9":{"judri":"section-sumti-based-descriptions.html","cmene":"sumti-based descriptions"},
"6.10":{"judri":"section-sumti-qualifiers.html","cmene":"sumti qualifiers"},
"6.11":{"judri":"section-vocative-syntax.html","cmene":"The syntax of vocative phrases"},
"6.12":{"judri":"section-names.html","cmene":"Lojban names"},
"6.13":{"judri":"section-pro-sumti.html","cmene":"Pro-sumti summary"},
"6.14":{"judri":"section-quotation.html","cmene":"Quotation summary"},
"6.15":{"judri":"section-number-summary.html","cmene":"Number summary"},
"7":{"judri":"chapter-anaphoric-cmavo.html","cmene":"Brevity Is The Soul Of Language: Pro-sumti And Pro-bridi"},
"7.1":{"judri":"chapter-anaphoric-cmavo.html#section-anaphoric-cmavo-introduction","cmene":"What are pro-sumti and pro-bridi? What are they for?"},
"7.2":{"judri":"section-mi-series.html","cmene":"Personal pro-sumti: the mi-series"},
"7.3":{"judri":"section-ti-series.html","cmene":"Demonstrative pro-sumti: the ti-series"},
"7.4":{"judri":"section-dihu-series.html","cmene":"Utterance pro-sumti: the di'u-series"},
"7.5":{"judri":"section-koha-broda-series.html","cmene":"Assignable pro-sumti and pro-bridi: the ko'a-series and the broda-series"},
"7.6":{"judri":"section-ri-gohi-series.html","cmene":"Anaphoric pro-sumti and pro-bridi: the ri-series and the go'i-series"},
"7.7":{"judri":"section-zohe-cohe-series.html","cmene":"Indefinite pro-sumti and pro-bridi: the zo'e-series and the co'e-series"},
"7.8":{"judri":"section-voha-series.html","cmene":"Reflexive and reciprocal pro-sumti: the vo'a-series"},
"7.9":{"judri":"section-sumti-and-bridi-questions.html","cmene":"sumti and bridi questions: ma and mo"},
"7.10":{"judri":"section-keha.html","cmene":"Relativized pro-sumti: ke'a"},
"7.11":{"judri":"section-cehu.html","cmene":"Abstraction focus pro-sumti: ce'u"},
"7.12":{"judri":"section-da-buha-series.html","cmene":"Bound variable pro-sumti and pro-bridi: the da-series and the bu'a-series"},
"7.13":{"judri":"section-daho.html","cmene":"Pro-sumti and pro-bridi cancelling"},
"7.14":{"judri":"section-du.html","cmene":"The identity predicate: du"},
"7.15":{"judri":"section-anaphoric-rafsi.html","cmene":"lujvo based on pro-sumti"},
"7.16":{"judri":"section-koha-summary.html","cmene":"KOhA cmavo by series"},
"7.17":{"judri":"section-goha-summary.html","cmene":"GOhA and other pro-bridi by series"},
"7.18":{"judri":"section-other-summary.html","cmene":"Other cmavo discussed in this chapter"},
"8":{"judri":"chapter-relative-clauses.html","cmene":"Relative Clauses, Which Make sumti Even More Complicated"},
"8.1":{"judri":"chapter-relative-clauses.html#section-poi","cmene":"What are you pointing at?"},
"8.2":{"judri":"section-noi.html","cmene":"Incidental relative clauses"},
"8.3":{"judri":"section-relative-phrases.html","cmene":"Relative phrases"},
"8.4":{"judri":"section-zihe.html","cmene":"Multiple relative clauses: zi'e"},
"8.5":{"judri":"section-voi.html","cmene":"Non-veridical relative clauses: voi"},
"8.6":{"judri":"section-descriptors.html","cmene":"Relative clauses and descriptors"},
"8.7":{"judri":"section-possessive-sumti.html","cmene":"Possessive sumti"},
"8.8":{"judri":"section-vuho.html","cmene":"Relative clauses and complex sumti: vu'o"},
"8.9":{"judri":"section-relative-clauses-and-vocatives.html","cmene":"Relative clauses in vocative phrases"},
"8.10":{"judri":"section-nesting.html","cmene":"Relative clauses within relative clauses"},
"8.11":{"judri":"section-relative-clause-cmavo-summary.html","cmene":"Index of relative clause cmavo"},
"9":{"judri":"chapter-sumti-tcita.html","cmene":"To Boston Via The Road Go I, With An Excursion Into The Land Of Modals"},
"9.1":{"judri":"chapter-sumti-tcita.html#section-sumti-tcita-introduction","cmene":"Introductory"},
"9.2":{"judri":"section-cu.html","cmene":"Standard bridi form: cu"},
"9.3":{"judri":"section-FA.html","cmene":"Tagging places: FA"},
"9.4":{"judri":"section-SE.html","cmene":"Conversion: SE"},
"9.5":{"judri":"section-selbri-modals.html","cmene":"Modal places: FIhO, FEhU"},
"9.6":{"judri":"section-BAI.html","cmene":"Modal tags: BAI"},
"9.7":{"judri":"section-causals.html","cmene":"Modal sentence connection: the causals"},
"9.8":{"judri":"section-modal-connectives.html","cmene":"Other modal connections"},
"9.9":{"judri":"section-modal-selbri.html","cmene":"Modal selbri"},
"9.10":{"judri":"section-modal-relative-phrases.html","cmene":"Modal relative phrases; Comparison"},
"9.11":{"judri":"section-mixed-connection.html","cmene":"Mixed modal connection"},
"9.12":{"judri":"section-modal-jai.html","cmene":"Modal conversion: JAI"},
"9.13":{"judri":"section-modal-negation.html","cmene":"Modal negation"},
"9.14":{"judri":"section-sticky-modals.html","cmene":"Sticky modals"},
"9.15":{"judri":"section-connected-modals.html","cmene":"Logical and non-logical connection of modals"},
"9.16":{"judri":"section-irregular-BAI.html","cmene":"CV'V cmavo of selma'o BAI with irregular forms"},
"9.17":{"judri":"section-all-BAI.html","cmene":"Complete table of BAI cmavo with rough English equivalents"},
"10":{"judri":"chapter-tenses.html","cmene":"Imaginary Journeys: The Lojban Space/Time Tense System"},
"10.1":{"judri":"chapter-tenses.html#section-tenses-introduction","cmene":"Introductory"},
"10.2":{"judri":"section-spatial-tenses.html","cmene":"Spatial tenses: FAhA and VA"},
"10.3":{"judri":"section-compound-spatial-tenses.html","cmene":"Compound spatial tenses"},
"10.4":{"judri":"section-temporal-tenses.html","cmene":"Temporal tenses: PU and ZI"},
"10.5":{"judri":"section-interval-sizes.html","cmene":"Interval sizes: VEhA and ZEhA"},
"10.6":{"judri":"section-vagueness.html","cmene":"Vague intervals and non-specific tenses"},
"10.7":{"judri":"section-dimensionality.html","cmene":"Dimensionality: VIhA"},
"10.8":{"judri":"section-movement.html","cmene":"Movement in space: MOhI"},
"10.9":{"judri":"section-interval-properties.html","cmene":"Interval properties: TAhE and roi"},
"10.10":{"judri":"section-event-contours.html","cmene":"Event contours: ZAhO and re'u"},
"10.11":{"judri":"section-fehe.html","cmene":"Space interval modifiers: FEhE"},
"10.12":{"judri":"section-tcita.html","cmene":"Tenses as sumti tcita"},
"10.13":{"judri":"section-sticky-tenses.html","cmene":"Sticky and multiple tenses: KI"},
"10.14":{"judri":"section-story-time.html","cmene":"Story time"},
"10.15":{"judri":"section-sub-bridi-tenses.html","cmene":"Tenses in subordinate bridi"},
"10.16":{"judri":"section-tense-connection.html","cmene":"Tense relations between sentences"},
"10.17":{"judri":"section-tense-logical-connection.html","cmene":"Tensed logical connectives"},
"10.18":{"judri":"section-tense-negation.html","cmene":"Tense negation"},
"10.19":{"judri":"section-caha.html","cmene":"Actuality, potentiality, capability: CAhA"},
"10.20":{"judri":"section-connected-tenses.html","cmene":"Logical and non-logical connections between tenses"},
"10.21":{"judri":"section-sub-events.html","cmene":"Sub-events"},
"10.22":{"judri":"section-jai.html","cmene":"Conversion of sumti tcita: JAI"},
"10.23":{"judri":"section-tenses-vs-modals.html","cmene":"Tenses versus modals"},
"10.24":{"judri":"section-tense-questions.html","cmene":"Tense questions: cu'e"},
"10.25":{"judri":"section-explicit-magnitudes.html","cmene":"Explicit magnitudes"},
"10.26":{"judri":"section-exercise.html","cmene":"Finally (an exercise for the much-tried reader)"},
"10.27":{"judri":"section-tense-selmaho-summary.html","cmene":"Summary of tense selma'o"},
"10.28":{"judri":"section-direction-cmavo.html","cmene":"List of spatial directions and direction-like relations"},
"11":{"judri":"chapter-abstractions.html","cmene":"Events, Qualities, Quantities, And Other Vague Words: On Lojban Abstraction"},
"11.1":{"judri":"chapter-abstractions.html#section-syntax","cmene":"The syntax of abstraction"},
"11.2":{"judri":"section-events.html","cmene":"Event abstraction"},
"11.3":{"judri":"section-event-types.html","cmene":"Types of event abstractions"},
"11.4":{"judri":"section-properties.html","cmene":"Property abstractions"},
"11.5":{"judri":"section-amounts.html","cmene":"Amount abstractions"},
"11.6":{"judri":"section-truth-values.html","cmene":"Truth-value abstraction: jei"},
"11.7":{"judri":"section-predications.html","cmene":"Predication/sentence abstraction"},
"11.8":{"judri":"section-indirect-questions.html","cmene":"Indirect questions"},
"11.9":{"judri":"section-minor-abstractions.html","cmene":"Minor abstraction types"},
"11.10":{"judri":"section-sumti-raising.html","cmene":"Lojban sumti raising"},
"11.11":{"judri":"section-events-and-contours.html","cmene":"Event-type abstractors and event contour tenses"},
"11.12":{"judri":"section-abstractor-connection.html","cmene":"Abstractor connection"},
"11.13":{"judri":"section-summary.html","cmene":"Table of abstractors"},
"12":{"judri":"chapter-lujvo.html","cmene":"Dog House And White House: Determining lujvo Place Structures"},
"12.1":{"judri":"chapter-lujvo.html#section-why-lujvo","cmene":"Why have lujvo?"},
"12.2":{"judri":"section-tanru-meanings.html","cmene":"The meaning of tanru: a necessary detour"},
"12.3":{"judri":"section-lujvo-meanings.html","cmene":"The meaning of lujvo"},
"12.4":{"judri":"section-selecting-places.html","cmene":"Selecting places"},
"12.5":{"judri":"section-symmetrical-asymmetrical.html","cmene":"Symmetrical and asymmetrical lujvo"},
"12.6":{"judri":"section-dependent-places.html","cmene":"Dependent places"},
"12.7":{"judri":"section-order-of-places.html","cmene":"Ordering lujvo places."},
"12.8":{"judri":"section-n-part-lujvo.html","cmene":"lujvo with more than two parts."},
"12.9":{"judri":"section-seltau-SE.html","cmene":"Eliding SE rafsi from seltau"},
"12.10":{"judri":"section-tertau-SE.html","cmene":"Eliding SE rafsi from tertau"},
"12.11":{"judri":"section-eliding-ke-kehe.html","cmene":"Eliding KE and KEhE rafsi from lujvo"},
"12.12":{"judri":"section-abstraction-lujvo.html","cmene":"Abstract lujvo"},
"12.13":{"judri":"section-implicit-abstraction.html","cmene":"Implicit-abstraction lujvo"},
"12.14":{"judri":"section-anomalous-lujvo.html","cmene":"Anomalous lujvo"},
"12.15":{"judri":"section-comparatives.html","cmene":"Comparatives and superlatives"},
"12.16":{"judri":"section-gismu-place-structures.html","cmene":"Notes on gismu place structures"},
"13":{"judri":"chapter-attitudinals.html","cmene":"Oooh! Arrgh! Ugh! Yecch! Attitudinal and Emotional Indicators"},
"13.1":{"judri":"chapter-attitudinals.html#section-attitudinals-introduction","cmene":"What are attitudinal indicators?"},
"13.2":{"judri":"section-pure-emotions.html","cmene":"Pure emotion indicators"},
"13.3":{"judri":"section-propositional-emotions.html","cmene":"Propositional attitude indicators"},
"13.4":{"judri":"section-intensity-scale.html","cmene":"Attitudes as scales"},
"13.5":{"judri":"section-attitudinal-space.html","cmene":"The space of emotions"},
"13.6":{"judri":"section-categories.html","cmene":"Emotional categories"},
"13.7":{"judri":"section-modifiers.html","cmene":"Attitudinal modifiers"},
"13.8":{"judri":"section-compound-attitudinals.html","cmene":"Compound indicators"},
"13.9":{"judri":"section-scope.html","cmene":"The uses of indicators"},
"13.10":{"judri":"section-questions-empathy-contours.html","cmene":"Attitude questions; empathy; attitude contours"},
"13.11":{"judri":"section-evidentials.html","cmene":"Evidentials"},
"13.12":{"judri":"section-discursives.html","cmene":"Discursives"},
"13.13":{"judri":"section-miscellanious.html","cmene":"Miscellaneous indicators"},
"13.14":{"judri":"section-vocative-scales.html","cmene":"Vocative scales"},
"13.15":{"judri":"section-sample-dialogue.html","cmene":"A sample dialogue"},
"13.16":{"judri":"section-attitudinals-conclusion.html","cmene":"Tentative conclusion"},
"14":{"judri":"chapter-connectives.html","cmene":"If Wishes Were Horses: The Lojban Connective System"},
"14.1":{"judri":"chapter-connectives.html#section-connectives-introduction","cmene":"Logical connection and truth tables"},
"14.2":{"judri":"section-four-basics.html","cmene":"The Four basic vowels"},
"14.3":{"judri":"section-six-types.html","cmene":"The six types of logical connectives"},
"14.4":{"judri":"section-bridi-connection.html","cmene":"Logical connection of bridi"},
"14.5":{"judri":"section-forethought-bridi-connection.html","cmene":"Forethought bridi connection"},
"14.6":{"judri":"section-sumti-connection.html","cmene":"sumti connection"},
"14.7":{"judri":"section-more-propositions.html","cmene":"More than two propositions"},
"14.8":{"judri":"section-afterthought-connectives-grouping.html","cmene":"Grouping of afterthought connectives"},
"14.9":{"judri":"section-compound-bridi.html","cmene":"Compound bridi"},
"14.10":{"judri":"section-multiple-compound-bridi.html","cmene":"Multiple compound bridi"},
"14.11":{"judri":"section-termsets.html","cmene":"Termset logical connection"},
"14.12":{"judri":"section-tanru.html","cmene":"Logical connection within tanru"},
"14.13":{"judri":"section-truth-and-connective-questions.html","cmene":"Truth questions and connective questions"},
"14.14":{"judri":"section-non-logical-connectives.html","cmene":"Non-logical connectives"},
"14.15":{"judri":"section-non-logical-continued.html","cmene":"More about non-logical connectives"},
"14.16":{"judri":"section-non-logical-continued-continued.html","cmene":"Interval connectives and forethought non-logical connection"},
"14.17":{"judri":"section-mekso-connections.html","cmene":"Logical and non-logical connectives within mekso"},
"14.18":{"judri":"section-sumtcita.html","cmene":"Tenses, modals, and logical connection"},
"14.19":{"judri":"section-abstractors.html","cmene":"Abstractor connection and connection within abstractions"},
"14.20":{"judri":"section-constructs-summary.html","cmene":"Constructs and appropriate connectives"},
"14.21":{"judri":"section-truth-functions-summary.html","cmene":"Truth functions and corresponding logical connectives"},
"14.22":{"judri":"section-construction-summary.html","cmene":"Rules for making logical and non-logical connectives"},
"14.23":{"judri":"section-other-tables.html","cmene":"Locations of other tables"},
"15":{"judri":"chapter-negation.html","cmene":"No” Problems: On Lojban Negation"},
"15.1":{"judri":"chapter-negation.html#section-negation-introduction","cmene":"Introductory"},
"15.2":{"judri":"section-bridi-negation.html","cmene":"bridi negation"},
"15.3":{"judri":"section-scalar-negation.html","cmene":"Scalar Negation"},
"15.4":{"judri":"section-nahe.html","cmene":"selbri and tanru negation"},
"15.5":{"judri":"section-scales-negation.html","cmene":"Expressing scales in selbri negation"},
"15.6":{"judri":"section-sumti-negation.html","cmene":"sumti negation"},
"15.7":{"judri":"section-other-negation.html","cmene":"Negation of minor grammatical constructs"},
"15.8":{"judri":"section-truth-questions.html","cmene":"Truth questions"},
"15.9":{"judri":"section-affirmations.html","cmene":"Affirmations"},
"15.10":{"judri":"section-metalinguistic-negation.html","cmene":"Metalinguistic negation forms"},
"15.11":{"judri":"section-are-all-questions-answered.html","cmene":"Summary – Are All Possible Questions About Negation Now Answered?"},
"16":{"judri":"chapter-quantifiers.html","cmene":"Who Did You Pass On The Road? Nobody”: Lojban And Logic"},
"16.1":{"judri":"chapter-quantifiers.html#section-quantifiers-introduction","cmene":"What's wrong with this picture?"},
"16.2":{"judri":"section-da-and-zohu.html","cmene":"Existential claims, prenexes, and variables"},
"16.3":{"judri":"section-universal-claims.html","cmene":"Universal claims"},
"16.4":{"judri":"section-restricted-claims.html","cmene":"Restricted claims: da poi"},
"16.5":{"judri":"section-prenex-elision.html","cmene":"Dropping the prenex"},
"16.6":{"judri":"section-quantified-variables.html","cmene":"Variables with generalized quantifiers"},
"16.7":{"judri":"section-quantifier-grouping.html","cmene":"Grouping of quantifiers"},
"16.8":{"judri":"section-any.html","cmene":"The problem of any”"},
"16.9":{"judri":"section-negation-boundaries.html","cmene":"Negation boundaries"},
"16.10":{"judri":"section-connectives.html","cmene":"bridi negation and logical connectives"},
"16.11":{"judri":"section-na-outside-prenex.html","cmene":"Using naku outside a prenex"},
"16.12":{"judri":"section-demorgans-law.html","cmene":"Logical Connectives and DeMorgan's Law"},
"16.13":{"judri":"section-selbri-variables.html","cmene":"selbri variables"},
"16.14":{"judri":"section-notes-on-variables.html","cmene":"A few notes on variables"},
"16.15":{"judri":"section-logic-conclusion.html","cmene":"Conclusion"},
"17":{"judri":"chapter-letterals.html","cmene":"As Easy As A-B-C? The Lojban Letteral System And Its Uses"},
"17.1":{"judri":"chapter-letterals.html#section-letterals-introduction","cmene":"What's a letteral, anyway?"},
"17.2":{"judri":"section-lerfu-liste.html","cmene":"A to Z in Lojban, plus one"},
"17.3":{"judri":"section-upper-case.html","cmene":"Upper and lower cases"},
"17.4":{"judri":"section-bu.html","cmene":"The universal bu"},
"17.5":{"judri":"section-alien-alphabets.html","cmene":"Alien alphabets"},
"17.6":{"judri":"section-accents.html","cmene":"Accent marks and compound lerfu words"},
"17.7":{"judri":"section-punctuation.html","cmene":"Punctuation marks"},
"17.8":{"judri":"section-chinese-characters.html","cmene":"What about Chinese characters?"},
"17.9":{"judri":"section-lerfu-pro-sumti.html","cmene":"lerfu words as pro-sumti"},
"17.10":{"judri":"section-meho.html","cmene":"References to lerfu"},
"17.11":{"judri":"section-math.html","cmene":"Mathematical uses of lerfu strings"},
"17.12":{"judri":"section-acronyms.html","cmene":"Acronyms"},
"17.13":{"judri":"section-character-codes.html","cmene":"Computerized character codes"},
"17.14":{"judri":"section-lerfu-cmavo-summary.html","cmene":"List of all auxiliary lerfu-word cmavo"},
"17.15":{"judri":"section-proposed-lerfu-words.html","cmene":"Proposed lerfu words – introduction"},
"17.16":{"judri":"section-greek.html","cmene":"Proposed lerfu words for the Greek alphabet"},
"17.17":{"judri":"section-cyrillic.html","cmene":"Proposed lerfu words for the Cyrillic alphabet"},
"17.18":{"judri":"section-hebrew.html","cmene":"Proposed lerfu words for the Hebrew alphabet"},
"17.19":{"judri":"section-accents-multiple-letters.html","cmene":"Proposed lerfu words for some accent marks and multiple letters"},
"17.20":{"judri":"section-ICAO-alphabet.html","cmene":"Proposed lerfu words for radio communication"},
"18":{"judri":"chapter-mekso.html","cmene":"lojbau mekso: Mathematical Expressions in Lojban"},
"18.1":{"judri":"chapter-mekso.html#section-mekso-introduction","cmene":"Introductory"},
"18.2":{"judri":"section-mekso-numbers.html","cmene":"Lojban numbers"},
"18.3":{"judri":"section-signs-punctuation.html","cmene":"Signs and numerical punctuation"},
"18.4":{"judri":"section-constants.html","cmene":"Special numbers"},
"18.5":{"judri":"section-simple-infix.html","cmene":"Simple infix expressions and equations"},
"18.6":{"judri":"section-forethought.html","cmene":"Forethought operators (Polish notation, functions)"},
"18.7":{"judri":"section-useful-selbri.html","cmene":"Other useful selbri for mekso bridi"},
"18.8":{"judri":"section-indefinite-numbers.html","cmene":"Indefinite numbers"},
"18.9":{"judri":"section-approximation.html","cmene":"Approximation and inexact numbers"},
"18.10":{"judri":"section-radixen.html","cmene":"Non-decimal and compound bases"},
"18.11":{"judri":"section-mekso-selbri.html","cmene":"Special mekso selbri"},
"18.12":{"judri":"section-number-questions.html","cmene":"Number questions"},
"18.13":{"judri":"section-subscripts-math.html","cmene":"Subscripts"},
"18.14":{"judri":"section-infix-again.html","cmene":"Infix operators revisited"},
"18.15":{"judri":"section-vectors-matrices.html","cmene":"Vectors and matrices"},
"18.16":{"judri":"section-reverse-polish-notation.html","cmene":"Reverse Polish notation"},
"18.17":{"judri":"section-connectives-within-mekso.html","cmene":"Logical and non-logical connectives within mekso"},
"18.18":{"judri":"section-lojban-within-mekso.html","cmene":"Using Lojban resources within mekso"},
"18.19":{"judri":"section-other-mekso-uses.html","cmene":"Other uses of mekso"},
"18.20":{"judri":"section-explicit-operator-precedence.html","cmene":"Explicit operator precedence"},
"18.21":{"judri":"section-miscellany.html","cmene":"Miscellany"},
"18.22":{"judri":"section-four-score-and-seven.html","cmene":"Four score and seven: a mekso problem"},
"18.23":{"judri":"section-selmaho-summary.html","cmene":"mekso selma'o summary"},
"18.24":{"judri":"section-vuhu.html","cmene":"Complete table of VUhU cmavo, with operand structures"},
"18.25":{"judri":"section-pa.html","cmene":"Complete table of PA cmavo: digits, punctuation, and other numbers."},
"18.26":{"judri":"section-moi.html","cmene":"Table of MOI cmavo, with associated rafsi and place structures"},
"19":{"judri":"chapter-structure.html","cmene":"Putting It All Together: Notes on the Structure of Lojban Texts"},
"19.1":{"judri":"chapter-structure.html#section-structure-introduction","cmene":"Introductory"},
"19.2":{"judri":"section-i.html","cmene":"Sentences: I"},
"19.3":{"judri":"section-niho.html","cmene":"Paragraphs: NIhO"},
"19.4":{"judri":"section-topic-comments.html","cmene":"Topic-comment sentences: ZOhU"},
"19.5":{"judri":"section-questions-and-answers.html","cmene":"Questions and answers"},
"19.6":{"judri":"section-subscripts-general.html","cmene":"Subscripts: XI"},
"19.7":{"judri":"section-utterance-ordinals.html","cmene":"Utterance ordinals: MAI"},
"19.8":{"judri":"section-attitudinal-scope.html","cmene":"Attitude scope markers: FUhE/FUhO"},
"19.9":{"judri":"section-quotations.html","cmene":"Quotations: LU, LIhU, LOhU, LEhU"},
"19.10":{"judri":"section-more-quotations.html","cmene":"More on quotations: ZO, ZOI"},
"19.11":{"judri":"section-bahe.html","cmene":"Contrastive emphasis: BAhE"},
"19.12":{"judri":"section-parentheses.html","cmene":"Parenthesis and metalinguistic commentary: TO, TOI, SEI"},
"19.13":{"judri":"section-erasure.html","cmene":"Erasure: SI, SA, SU"},
"19.14":{"judri":"section-hesitation.html","cmene":"Hesitation: Y"},
"19.15":{"judri":"section-faho.html","cmene":"No more to say: FAhO"},
"19.16":{"judri":"section-cmavo-interactions.html","cmene":"List of cmavo interactions"},
"19.17":{"judri":"section-elidable-terminators.html","cmene":"List of Elidable Terminators"},
"20":{"judri":"chapter-catalogue.html","cmene":"A Catalogue of selma'o"},
"20.1":{"judri":"chapter-catalogue.html#section-index","cmene":"A Catalogue Of selma'o"},
"21":{"judri":"chapter-grammars.html","cmene":"Formal Grammars"},
"21.1":{"judri":"chapter-grammars.html#section-EBNF","cmene":"EBNF Grammar of Lojban"},
"21.2":{"judri":"section-cross-reference.html","cmene":"EBNF Cross-Reference"}
};
