// JavaScript Document
window.nasezvafahi = 'not found';
window.rimni="la rimni sutysisku";
window.bangubuild = 'Building index...';
window.rimni="la rimni sutysisku";
window.bangudecomp = 'decomposing ...';
window.xuzganalojudri = true;
window.judri = "http://jbovlaste.lojban.org/dict/";
window.cllnotci = 'The Reference Grammar on this topic:';
window.purc = "Last searched: ";
window.rimni="la rimni sutysisku";
window.bangu=".inglic.";
window.arrcll = {
A:"https://lojban.github.io/cll/14/6/",
BAI:"https://lojban.github.io/cll/9/6/",
BAhE:"https://lojban.github.io/cll/19/11/",
BE:"https://lojban.github.io/cll/5/7/",
BEI:"https://lojban.github.io/cll/5/7/",
BEhO:"https://lojban.github.io/cll/5/7/",
BIhE:"https://lojban.github.io/cll/18/5/",
BIhI:"https://lojban.github.io/cll/14/16/",
BO:"https://lojban.github.io/cll/5/3/ https://lojban.github.io/cll/15/6/ https://lojban.github.io/cll/18/17/",
BOI:"https://lojban.github.io/cll/18/6/",
BU:"https://lojban.github.io/cll/17/4/",
BY:"https://lojban.github.io/cll/17/2/",
CAI:"https://lojban.github.io/cll/13/4/",
CAhA:"https://lojban.github.io/cll/10/19/",
CEI:"https://lojban.github.io/cll/7/5/",
CEhE:"https://lojban.github.io/cll/14/11/ https://lojban.github.io/cll/16/7/",
CO:"https://lojban.github.io/cll/5/8/",
COI:"https://lojban.github.io/cll/6/11/ https://lojban.github.io/cll/13/14/",
CU:"https://lojban.github.io/cll/9/2/",
CUhE:"https://lojban.github.io/cll/10/24/",
DAhO:"https://lojban.github.io/cll/7/13/",
DOI:"https://lojban.github.io/cll/13/14/",
DOhU:"https://lojban.github.io/cll/13/14/",
FA:"https://lojban.github.io/cll/9/3/",
FAhA:"https://lojban.github.io/cll/10/2/",
FAhO:"https://lojban.github.io/cll/19/15/",
FEhE:"https://lojban.github.io/cll/10/11/",
FEhU:"https://lojban.github.io/cll/9/5/",
FIhO:"https://lojban.github.io/cll/9/5/",
FOI:"https://lojban.github.io/cll/17/6/",
FUhA:"https://lojban.github.io/cll/18/16/",
FUhE:"https://lojban.github.io/cll/19/8/",
FUhO:"https://lojban.github.io/cll/19/8/",
GA:"https://lojban.github.io/cll/14/5/",
GAhO:"https://lojban.github.io/cll/14/16/",
GEhU:"https://lojban.github.io/cll/8/3/",
GI:"https://lojban.github.io/cll/14/5/",
GIhA:"https://lojban.github.io/cll/14/3/",
GOI:"https://lojban.github.io/cll/8/3/",
GOhA:"https://lojban.github.io/cll/7/6/",
GUhA:"https://lojban.github.io/cll/14/3/",
I:"https://lojban.github.io/cll/19/2/",
JA:"https://lojban.github.io/cll/14/3/",
JAI:"https://lojban.github.io/cll/9/12/",
JOI:"https://lojban.github.io/cll/14/14/",
JOhI:"https://lojban.github.io/cll/18/15/",
KE:"https://lojban.github.io/cll/5/5/",
KEI:"https://lojban.github.io/cll/11/1/",
KEhE:"https://lojban.github.io/cll/5/5/",
KI:"https://lojban.github.io/cll/10/13/",
KOhA:"https://lojban.github.io/cll/7/1/",
KOhA2:"https://lojban.github.io/cll/7/4/",
KOhA3:"https://lojban.github.io/cll/7/2/",
KOhA4:"https://lojban.github.io/cll/7/5/",
KOhA5:"https://lojban.github.io/cll/7/6/",
KOhA6:"https://lojban.github.io/cll/7/3/",
KOhA7:"https://lojban.github.io/cll/7/7/",
KU:"https://lojban.github.io/cll/6/2/ https://lojban.github.io/cll/10/1/",
KUhE:"https://lojban.github.io/cll/18/6/",
KUhO:"https://lojban.github.io/cll/8/1/",
LA:"https://lojban.github.io/cll/6/2/",
LAU:"https://lojban.github.io/cll/17/14/",
LAhE:"https://lojban.github.io/cll/6/10/",
LE:"https://lojban.github.io/cll/6/2/",
LEhU:"https://lojban.github.io/cll/19/9/",
LI:"https://lojban.github.io/cll/18/5/",
LIhU:"https://lojban.github.io/cll/19/9/",
LOhO:"https://lojban.github.io/cll/18/17/",
LOhU:"https://lojban.github.io/cll/19/9/",
LU:"https://lojban.github.io/cll/19/9/",
LUhU:"https://lojban.github.io/cll/6/10/",
MAI:"https://lojban.github.io/cll/18/19/ https://lojban.github.io/cll/19/1/",
MAhO:"https://lojban.github.io/cll/18/6/",
ME:"https://lojban.github.io/cll/5/10/ https://lojban.github.io/cll/18/1/",
MEhU:"https://lojban.github.io/cll/5/11/",
MOI:"https://lojban.github.io/cll/5/9/ https://lojban.github.io/cll/17/11/ https://lojban.github.io/cll/18/11/",
MOhE:"https://lojban.github.io/cll/18/18/",
MOhI:"https://lojban.github.io/cll/10/8/",
NA:"https://lojban.github.io/cll/14/3/ https://lojban.github.io/cll/15/7/",
NAI:"https://lojban.github.io/cll/14/3/ https://lojban.github.io/cll/15/7/",
NAhE:"https://lojban.github.io/cll/15/4/",
NAhU:"https://lojban.github.io/cll/18/18/",
NIhE:"https://lojban.github.io/cll/18/18/",
NIhO:"https://lojban.github.io/cll/19/3/",
NOI:"https://lojban.github.io/cll/8/1/",
NU:"https://lojban.github.io/cll/11/1/",
NUhA:"https://lojban.github.io/cll/18/19/",
NUhI:"https://lojban.github.io/cll/14/11/ https://lojban.github.io/cll/16/7/",
NUhU:"https://lojban.github.io/cll/14/11/",
PA:"https://lojban.github.io/cll/18/2/",
PEhE:"https://lojban.github.io/cll/14/11/",
PEhO:"https://lojban.github.io/cll/18/6/",
PU:"https://lojban.github.io/cll/10/4/",
RAhO:"https://lojban.github.io/cll/7/6/",
ROI:"https://lojban.github.io/cll/10/9/",
SA:"https://lojban.github.io/cll/19/13/",
SE:"https://lojban.github.io/cll/5/1/ https://lojban.github.io/cll/9/4/",
SEI:"https://lojban.github.io/cll/19/12/ https://lojban.github.io/cll/18/20/",
SEhU:"https://lojban.github.io/cll/19/12/",
SI:"https://lojban.github.io/cll/19/13/",
SOI:"https://lojban.github.io/cll/7/8/",
SU:"https://lojban.github.io/cll/19/13/",
TAhE:"https://lojban.github.io/cll/10/9/",
TEI:"https://lojban.github.io/cll/17/6/",
TEhU:"https://lojban.github.io/cll/18/15/",
TO:"https://lojban.github.io/cll/19/12/",
TOI:"https://lojban.github.io/cll/19/12/",
TUhE:"https://lojban.github.io/cll/19/2/",
TUhU:"https://lojban.github.io/cll/19/2/",
UI:"https://lojban.github.io/cll/13/1/",
UI1:"https://lojban.github.io/cll/13/2/ https://lojban.github.io/cll/13/3/",
UI2:"https://lojban.github.io/cll/13/11/",
UI3a:"https://lojban.github.io/cll/13/13/",
UI3b:"https://lojban.github.io/cll/13/12/",
UI4:"https://lojban.github.io/cll/13/6/",
UI5:"https://lojban.github.io/cll/13/7/",
UI6:"https://lojban.github.io/cll/13/13/",
VA:"https://lojban.github.io/cll/10/2/",
VAU:"https://lojban.github.io/cll/14/9/",
VEI:"https://lojban.github.io/cll/18/5/",
VEhA:"https://lojban.github.io/cll/10/5/",
VEhO:"https://lojban.github.io/cll/19/5/",
VIhA:"https://lojban.github.io/cll/10/7/",
VUhO:"https://lojban.github.io/cll/8/8/",
VUhU:"https://lojban.github.io/cll/18/5/",
VUhU1:"https://lojban.github.io/cll/18/5/ https://lojban.github.io/cll/14/17/ https://lojban.github.io/cll/5/9/ https://lojban.github.io/cll/9/8/",
VUhU2:"https://lojban.github.io/cll/18/14/",
VUhU4:"https://lojban.github.io/cll/18/15/",
XI:"https://lojban.github.io/cll/18/13/",
Y:"https://lojban.github.io/cll/19/14/",
ZAhO:"https://lojban.github.io/cll/10/10/",
ZEI:"https://lojban.github.io/cll/4/6/",
ZEhA:"https://lojban.github.io/cll/10/5/",
ZI:"https://lojban.github.io/cll/10/4/",
ZIhE:"https://lojban.github.io/cll/8/4/",
ZO:"https://lojban.github.io/cll/19/10/",
ZOI:"https://lojban.github.io/cll/19/10/",
ZOhU:"https://lojban.github.io/cll/16/2/ https://lojban.github.io/cll/19/4/"
};
